# Generated by Django 5.0.1 on 2024-02-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_number', models.CharField(max_length=10)),
                ('number_of_employees', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
