# Generated by Django 5.0.1 on 2024-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0006_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('position', models.CharField(max_length=100)),
                ('qualification_experience', models.TextField()),
                ('job_description', models.TextField()),
                ('event_date', models.DateField()),
                ('expected_salary', models.CharField(max_length=50)),
            ],
        ),
    ]
