# Generated by Django 5.0.1 on 2024-03-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0008_announcementtable_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_no', models.CharField(max_length=20)),
                ('number_of_employees', models.IntegerField(default=0)),
                ('manager', models.CharField(max_length=100)),
                ('progress', models.FloatField(default=0.0)),
            ],
        ),
    ]
