# Generated by Django 5.0.1 on 2024-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0010_project_employee_name1_project_employee_name2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_start_date', models.DateField()),
                ('employee_joined_day', models.DateField()),
                ('project_end_date', models.DateField()),
                ('num_assignments_completed', models.IntegerField()),
            ],
        ),
    ]
