# Generated by Django 5.0.1 on 2024-03-17 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0011_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='company1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('remark', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='job_applications/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TYApp.company1')),
            ],
        ),
    ]
