# Generated by Django 5.0.1 on 2024-03-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0012_company1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company1',
            name='company',
        ),
    ]
