# Generated by Django 5.0.1 on 2024-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0013_remove_company1_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('employee_count', models.IntegerField()),
            ],
        ),
    ]
