# Generated by Django 5.0.1 on 2024-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0014_companyemployeecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('remark', models.TextField()),
                ('document', models.FileField(upload_to='job_applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('remark', models.TextField()),
                ('document', models.FileField(upload_to='job_applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='company1',
        ),
    ]
