# Generated by Django 5.0.1 on 2024-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0015_jobapplication2_jobapplication3_delete_company1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='JobApplication3',
        ),
    ]
