# Generated by Django 5.0.1 on 2024-03-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0016_delete_assignment_delete_jobapplication3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
