# Generated by Django 5.0.1 on 2024-03-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TYApp', '0018_documentupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
